name: CI Variante D (flughafen-service)

on:
  push:
    branches: [ "feature/P3-**" ]
    paths:
      - "Code/P2/flughafen-service/**"
      - ".github/workflows/ci-variant-d-flughafen.yml"
      - ".github/workflows/_maven-service.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-variant-d-flughafen-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flughafen-service:
    uses: ./.github/workflows/_maven-service.yml
    with:
      service: flughafen-service
